"""[UPD] update data

Revision ID: 07136219f635
Revises: e5ec41aa1a8c
Create Date: 2025-11-24 14:36:48.651744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07136219f635'
down_revision: Union[str, Sequence[str], None] = 'e5ec41aa1a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('created_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
