"""[UPD] update model

Revision ID: 5c9215eb06e1
Revises: 
Create Date: 2025-11-24 18:23:21.854487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9215eb06e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_analisation',
    sa.Column('geo', sa.Integer(), nullable=True),
    sa.Column('geo_title', sa.String(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('average_kzt', sa.Integer(), nullable=True),
    sa.Column('rate_kzt', sa.Float(), nullable=True),
    sa.Column('calculated', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('min_average', sa.Float(), nullable=True),
    sa.Column('max_rate', sa.Float(), nullable=True),
    sa.Column('value_on_axis', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_title', 'last_updated', 'created_at', name='uq_geo_title_last_updated_created_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_analisation')
    # ### end Alembic commands ###
