"""[ADD] added model currency_rate

Revision ID: 93413fdcef18
Revises: 5c9215eb06e1
Create Date: 2025-11-24 19:35:29.976305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93413fdcef18'
down_revision: Union[str, Sequence[str], None] = '5c9215eb06e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rate',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('usd', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rate')
    # ### end Alembic commands ###
