"""[UPD] added rooms field

Revision ID: a420d3bdc935
Revises: 07136219f635
Create Date: 2025-11-24 14:53:53.883608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a420d3bdc935'
down_revision: Union[str, Sequence[str], None] = '07136219f635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('rooms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'rooms')
    # ### end Alembic commands ###
