"""[ADD] added model

Revision ID: cc072bdfc922
Revises: 93413fdcef18
Create Date: 2025-11-24 20:44:54.137398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc072bdfc922'
down_revision: Union[str, Sequence[str], None] = '93413fdcef18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_forecast',
    sa.Column('geo', sa.Integer(), nullable=False),
    sa.Column('geo_title', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_kzt', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('lower_bound_kzt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('upper_bound_kzt', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('building_forecast')
    # ### end Alembic commands ###
