"""[INIT] initial models

Revision ID: e5ec41aa1a8c
Revises: 
Create Date: 2025-11-24 13:27:03.021909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ec41aa1a8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('complex_Label', sa.String(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('price_per_area_metr', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predict_data',
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predict_data')
    op.drop_table('data')
    # ### end Alembic commands ###
